name: Build Docker Images
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image Tag'
        required: true
        default: 'latest'
      base_image:
        description: 'Base Editor Image'
        required: true
        default: 'nvidia/cuda:12.1.0-base-ubuntu22.04'

jobs:     
  build-editor-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            deserializeme/gamecx11
          tags: |
            "${{github.event.inputs.tag}}"
          
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile
          build-args: |
            module=${{github.event.inputs.module}}
            changeSet=${{github.event.inputs.change_set}}
            version=${{github.event.inputs.editor_version}}
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
