name: Build Docker Images
on:
  workflow_dispatch:
    inputs:
      base_image:
        description: 'GameCI Editor Image tag (Required)'
        required: true
        default: 'ubuntu-2022.1.23f1-webgl-1'
      nvidia_driver:
        description: 'Nvidia driver version (Optional)'
        default: '525.116.04'
jobs:     
  build-nvidia:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            deserializeme/editor
          
      - name: Login to dockerhub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./editor-nvidia/Dockerfile
          build-args: |
            EDITOR_IMAGE=unityci/editor:${{github.event.inputs.base_image}}
          context: ./editor-nvidia
          push: ${{ github.event_name != 'pull_request' }}
          tags: deserializeme/editor:${{github.event.inputs.base_image}}-nvidia
          labels: ${{ steps.meta.outputs.labels }}

  build-nvidia-baked:
    runs-on: [self-hosted]
    needs: build-nvidia
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            deserializeme/editor
          
      - name: Login to Harbor
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./editor-nvidia-baked/Dockerfile
          build-args: |
            EDITOR_IMAGE=deserializeme/editor:${{github.event.inputs.base_image}}-nvidia
            DRIVER_VERSION=${{github.event.inputs.nvidia_driver}}
          context: ./editor-nvidia-baked
          push: ${{ github.event_name != 'pull_request' }}
          tags: deserializeme/editor:${{github.event.inputs.base_image}}-nvidia-${{github.event.inputs.nvidia_driver}}
          labels: ${{ steps.meta.outputs.labels }}
